Repository TheMergers/eMerger, pull requests merged in 2021-07, with the labels that each got.

#51 Updater -> eMerger
  README.md
  fetch.sh
  setup.sh
  src/emerger.sh
  src/test/integrity_check.sh
Labels: refactor

#52 Bug fix
  setup.sh
  src/utils/cache_gen.sh
Labels: bug, high priority

#54 Add emoji :bug:
  setup.sh
  src/package/.packages
  src/package/arch.sh
  src/package/debian.sh
  src/package/flatpak.sh
  src/package/gentoo.sh
  src/package/opensuse.sh
  src/package/rpm.sh
  src/package/snap.sh
  src/package/termux.sh
  src/test/integrity_check.sh
  src/utils/cache_gen.sh
  src/utils/global.sh
  src/utils/privileges.sh
  src/utils/trash.sh
  uninstall.sh
Labels: enhancement

#55 Change README
  README.md
Labels: bug

#57 Few fixes
  LICENSE
  src/package/arch.sh
  src/package/debian.sh
  src/package/flatpak.sh
  src/package/gentoo.sh
  src/package/opensuse.sh
  src/package/rpm.sh
  src/package/snap.sh
  src/package/termux.sh
  src/utils/global.sh
  uninstall.sh
Labels: enhancement

#59 Change logo, add error tracking
  .gitignore
  setup.sh
  src/emerger.sh
  src/utils/.logo
  src/utils/global.sh
  uninstall.sh
Labels: enhancement

#61 Fix UI
  src/emerger.sh
Labels: Fix

#62 Add weather
  README.md
  license/WTTR_LICENSE
  src/emerger.sh
Labels: Fix, enhancement, low priority

#65 Fix retriever
  README.md
  src/emerger.sh
Labels: Fix

#67 Add NixOS - Fix README
  README.md
  src/package/.packages
  src/package/arch.sh
  src/package/debian.sh
  src/package/nix.sh
  src/utils/cache_gen.sh
  src/utils/global.sh
Labels: Fix, enhancement, low priority

#69 Add arguments
  CONTRIBUTING.md
  README.md
  src/emerger.sh
  src/utils/help
  src/utils/privileges.sh
  src/utils/trash.sh
Labels: documentation, enhancement

#72 Tests, auto-update and various fixes
  .gitignore
  README.md
  fetch.sh
  setup.sh
  src/emerger.sh
  src/package/.packages
  src/test/argument_check.sh
  src/test/integrity_check.sh
  src/test/list/.packages
  src/test/list/.tests
  src/test/list/.utils
  src/utils/.utils
  src/utils/cron.sh
  src/utils/global.sh
  src/utils/help
  uninstall.sh
  update.sh
Labels: Fix, bug, enhancement, refactor

#74 Refactor and add RPM
  README.md
  setup.sh
  src/emerger.sh
  src/package/debian.sh
  src/package/rpm.sh
  src/test/argument_check.sh
  src/utils/cache_gen.sh
  src/utils/cron.sh
  src/utils/global.sh
  src/utils/help
  uninstall.sh
Labels: Fix, enhancement, refactor

#75 Refactor and improve error tracking
  src/emerger.sh
  src/test/argument_check.sh
  src/test/integrity_check.sh
  src/utils/global.sh
  src/utils/help
Labels: enhancement, low priority, refactor

#76 Update README
  README.md
  src/utils/cron.sh
Labels: documentation

#77 Refactor
  src/emerger.sh
  src/test/argument_check.sh
  src/test/integrity_check.sh
  src/utils/cron.sh
  src/utils/global.sh
  src/utils/help
Labels: refactor

#79 Bug fix and refactor
  .gitignore
  README.md
  setup.sh
  src/emerger.sh
  src/package/arch.sh
  src/package/debian.sh
  src/package/flatpak.sh
  src/package/gentoo.sh
  src/package/nix.sh
  src/package/opensuse.sh
  src/package/rpm.sh
  src/package/snap.sh
  src/package/termux.sh
  src/test/argument_check.sh
  src/test/integrity_check.sh
  src/utils/cron.sh
  src/utils/global.sh
  src/utils/privileges.sh
  src/utils/trash.sh
  uninstall.sh
  update.sh
Labels: bug, enhancement, refactor

#81 :rocket: Improve error tracking
  src/emerger.sh
Labels: enhancement, refactor

#82 Small fix
  src/utils/cron.sh
Labels: bug, high priority
