Repository TheMergers/eMerger, pull requests merged in 2021-04, with the labels that each got.

#1 Added a couple of commands
  LICENSE
  README.md
  updater.sh
Labels: documentation, enhancement

#2 Add feature
  README.md
  updater.sh
Labels: enhancement

#3 Bug fix
  updater.sh
Labels: bug

#4 :lipstick: new colour and more
  updater.sh
Labels: enhancement

#5 :sparkles: added pacman
  updater.sh
Labels: enhancement

#6 Add Gentoo
  updater.sh
Labels: enhancement

#7 Add logo
  logo
  updater.sh
Labels: enhancement
