Repository TheMergers/eMerger, pull requests merged in 2021-06, with the labels that each got.

#23 Fixed path errors.
  src/privileges.sh
  src/updater.sh
Labels: bug, enhancement

#24 Add dnf autoremove
  AUTHORS
  README.md
  setup.sh
  src/updater.sh
  uninstall.sh
Labels: enhancement

#26 :file_folder: Create systems folder closes #20
  src/systems/archlinux.sh
  src/systems/debian.sh
  src/systems/fedora.sh
  src/systems/gentoo.sh
  src/systems/termux.sh
  src/updater.sh
Labels: enhancement

#27 Fix Termux, better UI, add flatpak and snap
  setup.sh
  src/package/archlinux.sh
  src/package/debian.sh
  src/package/flatpak.sh
  src/package/gentoo.sh
  src/package/rpm.sh
  src/package/snap.sh
  src/package/termux.sh
  src/updater.sh
  src/utils/.logo
  src/utils/global.sh
  src/utils/privileges.sh
  src/utils/trash.sh
  uninstall.sh
Labels: bug, enhancement

#29 Improve code
  setup.sh
  src/package/archlinux.sh
  src/package/debian.sh
  src/package/gentoo.sh
  src/package/rpm.sh
  src/package/termux.sh
  src/updater.sh
  src/utils/.logo
  src/utils/global.sh
  src/utils/privileges.sh
  src/utils/trash.sh
  uninstall.sh
Labels: enhancement

#30 Add and Fix
  src/package/archlinux.sh
  src/package/debian.sh
  src/package/flatpak.sh
  src/package/gentoo.sh
  src/package/rpm.sh
  src/package/snap.sh
  src/package/termux.sh
  src/updater.sh
  src/utils/privileges.sh
  src/utils/trash.sh
Labels: enhancement

#32 Add cache system
  .gitignore
  setup.sh
  src/package/archlinux.sh
  src/package/debian.sh
  src/package/flatpak.sh
  src/package/gentoo.sh
  src/package/rpm.sh
  src/package/snap.sh
  src/package/termux.sh
  src/updater.sh
  src/utils/cachegen.sh
  src/utils/checkpwr.sh
  src/utils/global.sh
  src/utils/trash.sh
  uninstall.sh
Labels: enhancement

#34 Solve #33
  .gitattributes
  AUTHORS
  setup.sh
  src/package/debian.sh
  src/package/flatpak.sh
  src/package/rpm.sh
  src/package/snap.sh
  src/updater.sh
  src/utils/cachegen.sh
  src/utils/global.sh
  src/utils/trash.sh
Labels: bug, medium priority

#35 Add zypper
  src/package/opensuse.sh
  src/utils/cachegen.sh
  src/utils/global.sh
Labels: enhancement

#36 :construction: Create test
  src/test/integrity_check.sh
Labels: enhancement, low priority

#37 Improved test file
  src/test/integrity_check.sh
  src/utils/package
  src/utils/utils
Labels: enhancement

#38 Refactor
  src/package/archlinux.sh
  src/package/debian.sh
  src/package/flatpak.sh
  src/package/gentoo.sh
  src/package/opensuse.sh
  src/package/rpm.sh
  src/package/snap.sh
  src/package/termux.sh
  src/test/integrity_check.sh
  src/updater.sh
  src/utils/.packages
  src/utils/.utils
  src/utils/global.sh
  src/utils/package
  src/utils/privileges.sh
  src/utils/utils
  uninstall.sh
Labels: enhancement, low priority

#39 Fix code
  src/updater.sh
Labels: enhancement, low priority

#40 Add mandatory test, fix #41
  setup.sh
  src/package/archlinux.sh
  src/package/debian.sh
  src/package/flatpak.sh
  src/package/gentoo.sh
  src/package/opensuse.sh
  src/package/rpm.sh
  src/package/snap.sh
  src/package/termux.sh
  src/test/integrity_check.sh
  src/updater.sh
  src/utils/.utils
  src/utils/cache_gen.sh
  src/utils/check_pwr.sh
Labels: bug, enhancement, medium priority

#42 Refactor
  src/test/integrity_check.sh
  src/utils/cache_gen.sh
Labels: refactor

#44 Refactor code
  setup.sh
  src/test/integrity_check.sh
  src/utils/cache_gen.sh
  uninstall.sh
Labels: enhancement, low priority, refactor

#45 :rocket: Added a fetch file to update from git
  fetch.sh
  setup.sh
  uninstall.sh
Labels: enhancement, low priority

#46 Refactor
  fetch.sh
  setup.sh
  src/updater.sh
  src/utils/cache_gen.sh
  uninstall.sh
Labels: enhancement, refactor

#47 Simplify
  AUTHORS
  LICENSE
  README.md
  fetch.sh
  src/utils/cache_gen.sh
Labels: low priority

#48 Move file
  src/package/.packages
  src/test/integrity_check.sh
Labels: refactor

#49 Modify debian
  src/package/debian.sh
Labels: enhancement
